# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sabberahamed/Documents/dynearthsol3d_energy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sabberahamed/Documents/dynearthsol3d_energy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sabberahamed/Documents/dynearthsol3d_energy/CMakeFiles /Users/sabberahamed/Documents/dynearthsol3d_energy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sabberahamed/Documents/dynearthsol3d_energy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dynearthsol2d

# Build rule for target.
dynearthsol2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dynearthsol2d
.PHONY : dynearthsol2d

# fast build rule for target.
dynearthsol2d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/build
.PHONY : dynearthsol2d/fast

#=============================================================================
# Target rules for targets named triangle

# Build rule for target.
triangle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle
.PHONY : triangle

# fast build rule for target.
triangle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle.dir/build.make CMakeFiles/triangle.dir/build
.PHONY : triangle/fast

#=============================================================================
# Target rules for targets named 3x3

# Build rule for target.
3x3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3x3
.PHONY : 3x3

# fast build rule for target.
3x3/fast:
	$(MAKE) $(MAKESILENT) -f 3x3-C/CMakeFiles/3x3.dir/build.make 3x3-C/CMakeFiles/3x3.dir/build
.PHONY : 3x3/fast

#=============================================================================
# Target rules for targets named ANN

# Build rule for target.
ANN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ANN
.PHONY : ANN

# fast build rule for target.
ANN/fast:
	$(MAKE) $(MAKESILENT) -f ann/CMakeFiles/ANN.dir/build.make ann/CMakeFiles/ANN.dir/build
.PHONY : ANN/fast

barycentric-fn.o: barycentric-fn.cxx.o
.PHONY : barycentric-fn.o

# target to build an object file
barycentric-fn.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/barycentric-fn.cxx.o
.PHONY : barycentric-fn.cxx.o

barycentric-fn.i: barycentric-fn.cxx.i
.PHONY : barycentric-fn.i

# target to preprocess a source file
barycentric-fn.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/barycentric-fn.cxx.i
.PHONY : barycentric-fn.cxx.i

barycentric-fn.s: barycentric-fn.cxx.s
.PHONY : barycentric-fn.s

# target to generate assembly for a file
barycentric-fn.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/barycentric-fn.cxx.s
.PHONY : barycentric-fn.cxx.s

bc.o: bc.cxx.o
.PHONY : bc.o

# target to build an object file
bc.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/bc.cxx.o
.PHONY : bc.cxx.o

bc.i: bc.cxx.i
.PHONY : bc.i

# target to preprocess a source file
bc.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/bc.cxx.i
.PHONY : bc.cxx.i

bc.s: bc.cxx.s
.PHONY : bc.s

# target to generate assembly for a file
bc.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/bc.cxx.s
.PHONY : bc.cxx.s

binaryio.o: binaryio.cxx.o
.PHONY : binaryio.o

# target to build an object file
binaryio.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/binaryio.cxx.o
.PHONY : binaryio.cxx.o

binaryio.i: binaryio.cxx.i
.PHONY : binaryio.i

# target to preprocess a source file
binaryio.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/binaryio.cxx.i
.PHONY : binaryio.cxx.i

binaryio.s: binaryio.cxx.s
.PHONY : binaryio.s

# target to generate assembly for a file
binaryio.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/binaryio.cxx.s
.PHONY : binaryio.cxx.s

brc-interpolation.o: brc-interpolation.cxx.o
.PHONY : brc-interpolation.o

# target to build an object file
brc-interpolation.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/brc-interpolation.cxx.o
.PHONY : brc-interpolation.cxx.o

brc-interpolation.i: brc-interpolation.cxx.i
.PHONY : brc-interpolation.i

# target to preprocess a source file
brc-interpolation.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/brc-interpolation.cxx.i
.PHONY : brc-interpolation.cxx.i

brc-interpolation.s: brc-interpolation.cxx.s
.PHONY : brc-interpolation.s

# target to generate assembly for a file
brc-interpolation.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/brc-interpolation.cxx.s
.PHONY : brc-interpolation.cxx.s

dynearthsol.o: dynearthsol.cxx.o
.PHONY : dynearthsol.o

# target to build an object file
dynearthsol.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/dynearthsol.cxx.o
.PHONY : dynearthsol.cxx.o

dynearthsol.i: dynearthsol.cxx.i
.PHONY : dynearthsol.i

# target to preprocess a source file
dynearthsol.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/dynearthsol.cxx.i
.PHONY : dynearthsol.cxx.i

dynearthsol.s: dynearthsol.cxx.s
.PHONY : dynearthsol.s

# target to generate assembly for a file
dynearthsol.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/dynearthsol.cxx.s
.PHONY : dynearthsol.cxx.s

fields.o: fields.cxx.o
.PHONY : fields.o

# target to build an object file
fields.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/fields.cxx.o
.PHONY : fields.cxx.o

fields.i: fields.cxx.i
.PHONY : fields.i

# target to preprocess a source file
fields.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/fields.cxx.i
.PHONY : fields.cxx.i

fields.s: fields.cxx.s
.PHONY : fields.s

# target to generate assembly for a file
fields.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/fields.cxx.s
.PHONY : fields.cxx.s

geometry.o: geometry.cxx.o
.PHONY : geometry.o

# target to build an object file
geometry.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/geometry.cxx.o
.PHONY : geometry.cxx.o

geometry.i: geometry.cxx.i
.PHONY : geometry.i

# target to preprocess a source file
geometry.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/geometry.cxx.i
.PHONY : geometry.cxx.i

geometry.s: geometry.cxx.s
.PHONY : geometry.s

# target to generate assembly for a file
geometry.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/geometry.cxx.s
.PHONY : geometry.cxx.s

ic-read-temp.o: ic-read-temp.cxx.o
.PHONY : ic-read-temp.o

# target to build an object file
ic-read-temp.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/ic-read-temp.cxx.o
.PHONY : ic-read-temp.cxx.o

ic-read-temp.i: ic-read-temp.cxx.i
.PHONY : ic-read-temp.i

# target to preprocess a source file
ic-read-temp.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/ic-read-temp.cxx.i
.PHONY : ic-read-temp.cxx.i

ic-read-temp.s: ic-read-temp.cxx.s
.PHONY : ic-read-temp.s

# target to generate assembly for a file
ic-read-temp.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/ic-read-temp.cxx.s
.PHONY : ic-read-temp.cxx.s

ic.o: ic.cxx.o
.PHONY : ic.o

# target to build an object file
ic.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/ic.cxx.o
.PHONY : ic.cxx.o

ic.i: ic.cxx.i
.PHONY : ic.i

# target to preprocess a source file
ic.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/ic.cxx.i
.PHONY : ic.cxx.i

ic.s: ic.cxx.s
.PHONY : ic.s

# target to generate assembly for a file
ic.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/ic.cxx.s
.PHONY : ic.cxx.s

input.o: input.cxx.o
.PHONY : input.o

# target to build an object file
input.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/input.cxx.o
.PHONY : input.cxx.o

input.i: input.cxx.i
.PHONY : input.i

# target to preprocess a source file
input.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/input.cxx.i
.PHONY : input.cxx.i

input.s: input.cxx.s
.PHONY : input.s

# target to generate assembly for a file
input.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/input.cxx.s
.PHONY : input.cxx.s

markerset.o: markerset.cxx.o
.PHONY : markerset.o

# target to build an object file
markerset.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/markerset.cxx.o
.PHONY : markerset.cxx.o

markerset.i: markerset.cxx.i
.PHONY : markerset.i

# target to preprocess a source file
markerset.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/markerset.cxx.i
.PHONY : markerset.cxx.i

markerset.s: markerset.cxx.s
.PHONY : markerset.s

# target to generate assembly for a file
markerset.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/markerset.cxx.s
.PHONY : markerset.cxx.s

matprops.o: matprops.cxx.o
.PHONY : matprops.o

# target to build an object file
matprops.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/matprops.cxx.o
.PHONY : matprops.cxx.o

matprops.i: matprops.cxx.i
.PHONY : matprops.i

# target to preprocess a source file
matprops.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/matprops.cxx.i
.PHONY : matprops.cxx.i

matprops.s: matprops.cxx.s
.PHONY : matprops.s

# target to generate assembly for a file
matprops.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/matprops.cxx.s
.PHONY : matprops.cxx.s

mesh.o: mesh.cxx.o
.PHONY : mesh.o

# target to build an object file
mesh.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/mesh.cxx.o
.PHONY : mesh.cxx.o

mesh.i: mesh.cxx.i
.PHONY : mesh.i

# target to preprocess a source file
mesh.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/mesh.cxx.i
.PHONY : mesh.cxx.i

mesh.s: mesh.cxx.s
.PHONY : mesh.s

# target to generate assembly for a file
mesh.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/mesh.cxx.s
.PHONY : mesh.cxx.s

nn-interpolation.o: nn-interpolation.cxx.o
.PHONY : nn-interpolation.o

# target to build an object file
nn-interpolation.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/nn-interpolation.cxx.o
.PHONY : nn-interpolation.cxx.o

nn-interpolation.i: nn-interpolation.cxx.i
.PHONY : nn-interpolation.i

# target to preprocess a source file
nn-interpolation.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/nn-interpolation.cxx.i
.PHONY : nn-interpolation.cxx.i

nn-interpolation.s: nn-interpolation.cxx.s
.PHONY : nn-interpolation.s

# target to generate assembly for a file
nn-interpolation.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/nn-interpolation.cxx.s
.PHONY : nn-interpolation.cxx.s

output.o: output.cxx.o
.PHONY : output.o

# target to build an object file
output.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/output.cxx.o
.PHONY : output.cxx.o

output.i: output.cxx.i
.PHONY : output.i

# target to preprocess a source file
output.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/output.cxx.i
.PHONY : output.cxx.i

output.s: output.cxx.s
.PHONY : output.s

# target to generate assembly for a file
output.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/output.cxx.s
.PHONY : output.cxx.s

phasechanges.o: phasechanges.cxx.o
.PHONY : phasechanges.o

# target to build an object file
phasechanges.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/phasechanges.cxx.o
.PHONY : phasechanges.cxx.o

phasechanges.i: phasechanges.cxx.i
.PHONY : phasechanges.i

# target to preprocess a source file
phasechanges.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/phasechanges.cxx.i
.PHONY : phasechanges.cxx.i

phasechanges.s: phasechanges.cxx.s
.PHONY : phasechanges.s

# target to generate assembly for a file
phasechanges.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/phasechanges.cxx.s
.PHONY : phasechanges.cxx.s

remeshing.o: remeshing.cxx.o
.PHONY : remeshing.o

# target to build an object file
remeshing.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/remeshing.cxx.o
.PHONY : remeshing.cxx.o

remeshing.i: remeshing.cxx.i
.PHONY : remeshing.i

# target to preprocess a source file
remeshing.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/remeshing.cxx.i
.PHONY : remeshing.cxx.i

remeshing.s: remeshing.cxx.s
.PHONY : remeshing.s

# target to generate assembly for a file
remeshing.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/remeshing.cxx.s
.PHONY : remeshing.cxx.s

rheology.o: rheology.cxx.o
.PHONY : rheology.o

# target to build an object file
rheology.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/rheology.cxx.o
.PHONY : rheology.cxx.o

rheology.i: rheology.cxx.i
.PHONY : rheology.i

# target to preprocess a source file
rheology.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/rheology.cxx.i
.PHONY : rheology.cxx.i

rheology.s: rheology.cxx.s
.PHONY : rheology.s

# target to generate assembly for a file
rheology.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/rheology.cxx.s
.PHONY : rheology.cxx.s

triangle/triangle.o: triangle/triangle.c.o
.PHONY : triangle/triangle.o

# target to build an object file
triangle/triangle.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle.dir/build.make CMakeFiles/triangle.dir/triangle/triangle.c.o
.PHONY : triangle/triangle.c.o

triangle/triangle.i: triangle/triangle.c.i
.PHONY : triangle/triangle.i

# target to preprocess a source file
triangle/triangle.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle.dir/build.make CMakeFiles/triangle.dir/triangle/triangle.c.i
.PHONY : triangle/triangle.c.i

triangle/triangle.s: triangle/triangle.c.s
.PHONY : triangle/triangle.s

# target to generate assembly for a file
triangle/triangle.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle.dir/build.make CMakeFiles/triangle.dir/triangle/triangle.c.s
.PHONY : triangle/triangle.c.s

vtk_output.o: vtk_output.cxx.o
.PHONY : vtk_output.o

# target to build an object file
vtk_output.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/vtk_output.cxx.o
.PHONY : vtk_output.cxx.o

vtk_output.i: vtk_output.cxx.i
.PHONY : vtk_output.i

# target to preprocess a source file
vtk_output.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/vtk_output.cxx.i
.PHONY : vtk_output.cxx.i

vtk_output.s: vtk_output.cxx.s
.PHONY : vtk_output.s

# target to generate assembly for a file
vtk_output.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynearthsol2d.dir/build.make CMakeFiles/dynearthsol2d.dir/vtk_output.cxx.s
.PHONY : vtk_output.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... 3x3"
	@echo "... ANN"
	@echo "... dynearthsol2d"
	@echo "... triangle"
	@echo "... barycentric-fn.o"
	@echo "... barycentric-fn.i"
	@echo "... barycentric-fn.s"
	@echo "... bc.o"
	@echo "... bc.i"
	@echo "... bc.s"
	@echo "... binaryio.o"
	@echo "... binaryio.i"
	@echo "... binaryio.s"
	@echo "... brc-interpolation.o"
	@echo "... brc-interpolation.i"
	@echo "... brc-interpolation.s"
	@echo "... dynearthsol.o"
	@echo "... dynearthsol.i"
	@echo "... dynearthsol.s"
	@echo "... fields.o"
	@echo "... fields.i"
	@echo "... fields.s"
	@echo "... geometry.o"
	@echo "... geometry.i"
	@echo "... geometry.s"
	@echo "... ic-read-temp.o"
	@echo "... ic-read-temp.i"
	@echo "... ic-read-temp.s"
	@echo "... ic.o"
	@echo "... ic.i"
	@echo "... ic.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... markerset.o"
	@echo "... markerset.i"
	@echo "... markerset.s"
	@echo "... matprops.o"
	@echo "... matprops.i"
	@echo "... matprops.s"
	@echo "... mesh.o"
	@echo "... mesh.i"
	@echo "... mesh.s"
	@echo "... nn-interpolation.o"
	@echo "... nn-interpolation.i"
	@echo "... nn-interpolation.s"
	@echo "... output.o"
	@echo "... output.i"
	@echo "... output.s"
	@echo "... phasechanges.o"
	@echo "... phasechanges.i"
	@echo "... phasechanges.s"
	@echo "... remeshing.o"
	@echo "... remeshing.i"
	@echo "... remeshing.s"
	@echo "... rheology.o"
	@echo "... rheology.i"
	@echo "... rheology.s"
	@echo "... triangle/triangle.o"
	@echo "... triangle/triangle.i"
	@echo "... triangle/triangle.s"
	@echo "... vtk_output.o"
	@echo "... vtk_output.i"
	@echo "... vtk_output.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

